### ISSUE TITLE
 ./bin/channels ( Error )

### ISSUE THREAD

**Issue by fitreklam** [englercj/node-esl#65]
Hello

I am getting the following error.

Please help me with this.

----------------------------------------------------------------
root@ajenti:/var/www/fusionpbx/cti/node_modules/modesl/examples/channels# ./bin/channels

module.js:340
    throw err;
          ^
Error: Cannot find module '../config.json'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at new exports.Api (/var/www/fusionpbx/cti/node_modules/modesl/examples/channels/lib/api.js:10:19)
    at Object.<anonymous> (/var/www/fusionpbx/cti/node_modules/modesl/examples/channels/bin/channels:4:7)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

**Comment by englercj** [comment]
First copy the `config.json.template` file to `config.json` and edit it as needed. Then run the service.

**Comment by fitreklam** [comment]
Hi
Thank you.

Now I am getting such a mistake.

---------------------------------------------------------------------
root@ajenti:/var/www/fusionpbx/cti/node_modules/modesl/examples/channels# ./bin/channels
Option log level is not valid. Please refer to the README.

/var/www/fusionpbx/cti/node_modules/modesl/examples/channels/lib/api.js:84
            socket.set('method', method, function() {
                   ^
TypeError: Object #<Socket> has no method 'set'
    at Socket.<anonymous> (/var/www/fusionpbx/cti/node_modules/modesl/examples/channels/lib/api.js:84:20)
    at Socket.emit (events.js:98:17)
    at /var/www/fusionpbx/cti/node_modules/modesl/examples/channels/node_modules/socket.io/lib/socket.js:503:12
    at process._tickCallback (node.js:419:13)
root@ajenti:/var/www/fusionpbx/cti/node_modules/modesl/examples/channels#

**Comment by englercj** [comment]
What version of socket.io do you have installed (`npm ls`).

**Comment by fitreklam** [comment]
Hi

This version is installed.
socket.io@1.7.4

**Comment by englercj** [comment]
Try installing `1.3.7` and seeing if that fixes your issue. They may have done a breaking change in a minor version.

**Comment by fitreklam** [comment]
Hi

Now I am getting such a mistake.

Missing error handler on `socket`.
TypeError: Object #<Socket> has no method 'set'
    at Socket.<anonymous> (/root/node-esl/examples/channels/lib/api.js:84:20)
    at Socket.emit (events.js:98:17)
    at Socket.onevent (/root/node-esl/examples/channels/node_modules/socket.io/lib/socket.js:330:8)
    at Socket.onpacket (/root/node-esl/examples/channels/node_modules/socket.io/lib/socket.js:290:12)
    at Client.ondecoded (/root/node-esl/examples/channels/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/root/node-esl/examples/channels/node_modules/socket.io/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/root/node-esl/examples/channels/node_modules/socket.io/node_modules/socket.io-parser/index.js:247:12)
    at Client.ondata (/root/node-esl/examples/channels/node_modules/socket.io/lib/client.js:175:18)
    at Socket.emit (events.js:95:17)
    at Socket.onPacket (/root/node-esl/examples/channels/node_modules/socket.io/node_modules/engine.io/lib/socket.js:99:14)

**Comment by englercj** [comment]
Ok, if you pull the latest of this repo it should fix the issue you are having. Looks like socket.io broke some APIs I used a long time ago when i originally wrote this.

**Comment by englercj** [comment]
Going to close this now since I believe it is fixed.
